# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c154b94dd2a904896d971585fc3fc27cdfb7a836a558cb34c36a7d04c960aed972af9e8915312deb4277f0a235083d83fb5520e20a252daffa6730c870b758f7

test:
  secret_key_base: fc39f6a37b3b9af9630be7aa04343d9bc29d9b79ca5d4232b2b66ca1421acd0a0e287bf25156a81eaab065df6c3042d196bb93d3f557ffd54fd16c051ec17e2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
